site_name: My Docs
theme:
  name: material

plugins:
  - tags:
      tags_extra_files:
        Documentation/anotherTagsIndex.md:
          - docs2
        Tutorials/tagsIndex.md:
          - docs1

extra:
  tags:
    docs1: docs1
    docs2: docs2


markdown_extensions:
  - meta

